class Payment {
  final String id;
  final String customerId;
  final String agentId;
  final double amountPaid;
  final int? boxesEquivalent;
  final DateTime timestamp;
  
  // Optional fields for joins
  final String? customerName;
  final String? agentName;
  final String? productName;

  const Payment({
    required this.id,
    required this.customerId,
    required this.agentId,
    required this.amountPaid,
    this.boxesEquivalent,
    required this.timestamp,
    this.customerName,
    this.agentName,
    this.productName,
  });

  factory Payment.fromJson(Map<String, dynamic> json) {
    return Payment(
      id: json['id'] as String,
      customerId: json['customer_id'] as String,
      agentId: json['agent_id'] as String,
      amountPaid: (json['amount_paid'] as num).toDouble(),
      boxesEquivalent: json['boxes_equivalent'] as int?,
      timestamp: DateTime.parse(json['timestamp'] as String),
      customerName: json['customer_name'] as String?,
      agentName: json['agent_name'] as String?,
      productName: json['product_name'] as String?,
    );
  }

  Map<String, dynamic> toJson() {
    return {
      'customer_id': customerId,
      'agent_id': agentId,
      'amount_paid': amountPaid,
      // timestamp is auto-generated by DB
    };
  }

  Payment copyWith({
    String? id,
    String? customerId,
    String? agentId,
    double? amountPaid,
    int? boxesEquivalent,
    DateTime? timestamp,
    String? customerName,
    String? agentName,
    String? productName,
  }) {
    return Payment(
      id: id ?? this.id,
      customerId: customerId ?? this.customerId,
      agentId: agentId ?? this.agentId,
      amountPaid: amountPaid ?? this.amountPaid,
      boxesEquivalent: boxesEquivalent ?? this.boxesEquivalent,
      timestamp: timestamp ?? this.timestamp,
      customerName: customerName ?? this.customerName,
      agentName: agentName ?? this.agentName,
      productName: productName ?? this.productName,
    );
  }
}
