class Payment {
  final String id;
  final String customerId;
  final String agentId;
  final double amountPaid;
  final String? productId; // Direct link to product (new)
  final int? boxesEquivalent;
  final DateTime timestamp;
  
  // Optional fields for joins
  final String? customerName;
  final String? agentName;
  final String? productName;

  const Payment({
    required this.id,
    required this.customerId,
    required this.agentId,
    required this.amountPaid,
    this.boxesEquivalent,
    required this.timestamp,
    this.productId,
    this.customerName,
    this.agentName,
    this.productName,
  });

  factory Payment.fromJson(Map<String, dynamic> json) {
    // Helper to safely parse int from either int or String
    int? parseIntOrNull(dynamic value) {
      if (value == null) return null;
      if (value is int) return value;
      return int.tryParse(value.toString());
    }

    double parseDoubleOrZero(dynamic value) {
      if (value == null) return 0.0;
      if (value is num) return value.toDouble();
      return double.tryParse(value.toString()) ?? 0.0;
    }

    return Payment(
      id: json['id'] as String,
      customerId: json['customer_id'] as String,
      agentId: json['agent_id'] as String,
      amountPaid: parseDoubleOrZero(json['amount_paid']),
      boxesEquivalent: parseIntOrNull(json['boxes_equivalent']),
      timestamp: DateTime.parse(json['timestamp'] as String),
      productId: json['product_id']?.toString(),
      customerName: json['customer_name'] as String?,
      agentName: json['agent_name'] as String?,
      productName: json['product_name'] as String?,
    );
  }

  Map<String, dynamic> toJson() {
    return {
      'customer_id': customerId,
      'agent_id': agentId,
      'amount_paid': amountPaid,
      if (productId != null) 'product_id': int.tryParse(productId!),
      // timestamp is auto-generated by DB
    };
  }

  Payment copyWith({
    String? id,
    String? customerId,
    String? agentId,
    double? amountPaid,
    int? boxesEquivalent,
    DateTime? timestamp,
    String? productId,
    String? customerName,
    String? agentName,
    String? productName,
  }) {
    return Payment(
      id: id ?? this.id,
      customerId: customerId ?? this.customerId,
      agentId: agentId ?? this.agentId,
      amountPaid: amountPaid ?? this.amountPaid,
      boxesEquivalent: boxesEquivalent ?? this.boxesEquivalent,
      timestamp: timestamp ?? this.timestamp,
      productId: productId ?? this.productId,
      customerName: customerName ?? this.customerName,
      agentName: agentName ?? this.agentName,
      productName: productName ?? this.productName,
    );
  }
}
